crop_attributes = {
    'apple': {'categories': ['Fruits'], 'duration': 'Long'},
    'banana': {'categories': ['Fruits'], 'duration': 'Long'},
    'blackgram': {'categories': ['Pulses'], 'duration': 'Short'},
    'chickpea': {'categories': ['Pulses'], 'duration': 'Medium'},
    'coconut': {'categories': ['Commercial'], 'duration': 'Long'},
    'coffee': {'categories': ['Commercial'], 'duration': 'Long'},
    'cotton': {'categories': ['Commercial'], 'duration': 'Long'},
    'grapes': {'categories': ['Fruits'], 'duration': 'Long'},
    'jute': {'categories': ['Commercial'], 'duration': 'Medium'},
    'kidneybeans': {'categories': ['Pulses'], 'duration': 'Short'},
    'lentil': {'categories': ['Pulses'], 'duration': 'Short'},
    'maize': {'categories': ['Grains'], 'duration': 'Medium'},
    'mango': {'categories': ['Fruits'], 'duration': 'Long'},
    'mothbeans': {'categories': ['Pulses'], 'duration': 'Short'},
    'mungbean': {'categories': ['Pulses'], 'duration': 'Short'},
    'muskmelon': {'categories': ['Fruits'], 'duration': 'Short'},
    'orange': {'categories': ['Fruits'], 'duration': 'Long'},
    'papaya': {'categories': ['Fruits'], 'duration': 'Long'},
    'pigeonpeas': {'categories': ['Pulses'], 'duration': 'Medium'},
    'pomegranate': {'categories': ['Fruits'], 'duration': 'Long'},
    'rice': {'categories': ['Grains'], 'duration': 'Medium'},
    'watermelon': {'categories': ['Fruits'], 'duration': 'Short'},
}
